[package]
name = "tip-router-operator-cli"
version = "0.1.0"
edition = "2021"
description = "CLI for Jito Tip Router"

[dependencies]
anyhow = "1.0"
bincode = "1.3"
clap = { version = "4.4", features = ["derive", "env"] }
crossbeam-channel = "0.5"
ellipsis-client = "0.1"
env_logger = "0.10"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
solana-accounts-db = "1.18.26"
solana-cli-config = "1.18.26"
solana-sdk = "1.18.26"
solana-client = "1.18.26"
solana-ledger = "1.18.26"
solana-runtime = "1.18.26"
solana-stake-program = "1.18.26"
solana-metrics = "1.18.26"
solana-vote-program = "1.18.26"
tempfile = "3.2"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
tokio-test = "0.4"