[package]
name = "tip-router-operator-cli"
version = "0.1.0"
edition = "2021"
description = "CLI for Jito Tip Router"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["derive", "env"] }
env_logger = "0.10"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
solana-sdk = "1.17"
solana-client = "1.17"
solana-cli-config = "1.17"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }